Rewrite
MoOx/reduce-css-calc pull request #21
Opened 2017-03-01 02:30 UTC by andyjansson

This rewrite is done with the intent of fixing inconsistent behaviour between reduce-css-calc and the W3C specification, as well as enabling better optimisation of `calc()` expressions. The rewrite is done from the ground-up in ES6 while still staying compatible with the existing API. It reduces `calc()` functions by transforming ASTs generated from the expressions.  

The rewrite also solves the following issues:

* moOx/reduce-css-calc#3
* moOx/reduce-css-calc#2
* moOx/reduce-css-calc#1
* postcss/postcss-calc#33
* postcss/postcss-calc#25
* ben-eb/cssnano#320
* ben-eb/cssnano#319
* ben-eb/cssnano#211

2017-03-01 07:01 UTC, MoOx requested changes
not sure it's a good idea to have postcss as a dep for a non postcss project... (I had in mind that other stuff like rework might use it).
If that's too postcss related why not merging this with postcss-calc directly?

Also it seems you don't cover all previous tests with the new tests so regressions are possible. Any reason to not keep previous tests in addition to new ones?

2017-03-01 07:01 UTC, MoOx commented on .babelrc
> +  "presets": ["es2015-loose", "stage-0"],
why not "just" babel-preset-latest?

2017-03-01 07:01 UTC, MoOx commented on .eslintrc
> +---
Any preset maybe?

2017-03-01 07:01 UTC, MoOx commented on package.json
> +    "LICENSE"
LICENSE is unecessary and automatic like README

2017-03-01 07:28 UTC, andyjansson commented
@MoOx it's not dependent upon postcss. It might just be some leftover copypasta from the postcss-calc rewrite. I'll fix it when I get home from work.

2017-05-07 11:06 UTC, ben-eb commented on .eslintrc
> +---
@MoOx https://github.com/MoOx/eslint-config-i-am-meticulous ? 😄

2017-05-07 11:18 UTC, MoOx commented on .eslintrc
> +---
Why not

2017-05-07 12:24 UTC, ben-eb commented
https://github.com/MoOx/reduce-css-calc/issues/22 supersedes this pull request.

2017-05-07 12:24 UTC, closed without merging